apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvcm-api
spec:
  selector:
    matchLabels:
      app: mvcm-api
  replicas: 1
  template:
    metadata:
      labels:
        app: mvcm-api
    spec:
      containers:
        - name: mvcm-api
          image: hdruk/mvcm-api:latest
          ports:
            - containerPort: 8080
              name: mvcm-api
      dnsPolicy: ClusterFirst